arrowParens: always
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
insertPragma: false
singleAttributePerLine: false
bracketSameLine: false
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 100
proseWrap: preserve
quoteProps: consistent
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
embeddedLanguageFormatting: auto
vueIndentScriptAndStyle: false
experimentalTernaries: false
parser: typescript
